import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

/**
 * Users table — multi-user support with role-based access
 */
export const users = sqliteTable("users", {
  id: text("id").primaryKey(), // nanoid
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  role: text("role", { enum: ["admin", "editor"] }).default("editor").notNull(),
  createdAt: text("created_at").notNull(), // ISO 8601
  updatedAt: text("updated_at").notNull(),
});

/**
 * Content items — pending, scheduled, and posted content
 * Scoped to userId for row-level security
 */
export const contentItems = sqliteTable("content_items", {
  id: text("id").primaryKey(), // nanoid
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  // Metadata from image_analyzer.py
  imageId: text("image_id").notNull(), // f1, f2, etc from analyzer
  sourceFile: text("source_file").notNull(), // {imageId}_metadata.json
  qualityScore: integer("quality_score").notNull(), // 0-100

  // Image URLs (Dropbox shared links with ?raw=1)
  igImageUrl: text("ig_image_url").notNull(),
  fbImageUrl: text("fb_image_url").notNull(),

  // Source metadata
  description: text("description"),
  mood: text("mood"),

  // Status — separate per platform for partial publish handling
  fbStatus: text("fb_status", {
    enum: ["pending", "scheduled", "published", "failed", "retry"],
  })
    .default("pending")
    .notNull(),
  igStatus: text("ig_status", {
    enum: ["pending", "scheduled", "published", "failed", "retry"],
  })
    .default("pending")
    .notNull(),

  // Published post IDs (for idempotency)
  fbPostId: text("fb_post_id"),
  igPostId: text("ig_post_id"),

  // Scheduling
  scheduledForFb: text("scheduled_for_fb"), // ISO 8601
  scheduledForIg: text("scheduled_for_ig"), // ISO 8601
  publishedAtFb: text("published_at_fb"), // ISO 8601
  publishedAtIg: text("published_at_ig"), // ISO 8601

  // Metadata
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

/**
 * Caption options — the 5 angles generated by image_analyzer.py
 * User selects one before approval
 */
export const captionOptions = sqliteTable("caption_options", {
  id: text("id").primaryKey(), // nanoid
  contentId: text("content_id")
    .notNull()
    .references(() => contentItems.id, { onDelete: "cascade" }),

  angle: text("angle").notNull(), // excitement, behind_scenes, etc
  caption: text("caption").notNull(), // Full caption text
  hashtags: text("hashtags"), // JSON array of hashtags
  selected: integer("selected", { mode: "boolean" }).default(false).notNull(),

  createdAt: text("created_at").notNull(),
});

/**
 * Hashtag sets — Instagram and Facebook hashtag lists
 * Could be reused across posts or per-post customization
 */
export const hashtagSets = sqliteTable("hashtag_sets", {
  id: text("id").primaryKey(), // nanoid
  contentId: text("content_id")
    .notNull()
    .references(() => contentItems.id, { onDelete: "cascade" }),

  platform: text("platform", { enum: ["instagram", "facebook"] }).notNull(),
  hashtags: text("hashtags").notNull(), // Space-separated #tags
  custom: integer("custom", { mode: "boolean" }).default(false).notNull(), // User-edited

  createdAt: text("created_at").notNull(),
});

/**
 * Post metrics — performance tracking (Phase 3)
 * Populated by webhooks from Meta
 */
export const postMetrics = sqliteTable("post_metrics", {
  id: text("id").primaryKey(), // nanoid
  contentId: text("content_id")
    .notNull()
    .references(() => contentItems.id, { onDelete: "cascade" }),

  platform: text("platform", {
    enum: ["facebook", "instagram"],
  }).notNull(),
  postId: text("post_id").notNull(), // fbPostId or igPostId

  likes: integer("likes").default(0),
  comments: integer("comments").default(0),
  shares: integer("shares").default(0),
  impressions: integer("impressions").default(0),
  reach: integer("reach").default(0),
  engagementRate: real("engagement_rate").default(0),

  lastSyncedAt: text("last_synced_at"), // ISO 8601
  createdAt: text("created_at").notNull(),
});

/**
 * Relations for Drizzle ORM
 */
export const usersRelations = relations(users, ({ many }) => ({
  contentItems: many(contentItems),
}));

export const contentItemsRelations = relations(
  contentItems,
  ({ one, many }) => ({
    user: one(users, {
      fields: [contentItems.userId],
      references: [users.id],
    }),
    captions: many(captionOptions),
    hashtags: many(hashtagSets),
    metrics: many(postMetrics),
  })
);

export const captionOptionsRelations = relations(
  captionOptions,
  ({ one }) => ({
    content: one(contentItems, {
      fields: [captionOptions.contentId],
      references: [contentItems.id],
    }),
  })
);

export const hashtagSetsRelations = relations(hashtagSets, ({ one }) => ({
  content: one(contentItems, {
    fields: [hashtagSets.contentId],
    references: [contentItems.id],
  }),
}));

export const postMetricsRelations = relations(postMetrics, ({ one }) => ({
  content: one(contentItems, {
    fields: [postMetrics.contentId],
    references: [contentItems.id],
  }),
}));
